#version 22-12-2024
#more info on https://github.com/kurz-schluss/esp32-keyble-ha
#author: kurz-schluss

mqtt:
  lock:
    - name: Schloss Haustür Antrieb
      state_topic: "homeassistant/lock/door/state"
      command_topic: "homeassistant/lock/door/command"
      payload_lock: "3"
      payload_unlock: "2"
      payload_open: "4"
      state_locked: "locked"
      state_unlocked: "unlocked"
      state_locking: "moving"
      state_unlocking: "moving"
      state_jammed: "timeout"
      optimistic: false


  binary_sensor:
    - name: Schloss Haustür Batterie Status
      state_topic: "homeassistant/lock/door/battery"
      payload_on: "false"
      payload_off: "true"
      device_class: battery
  button:
    - name: Schloss Haustür abfragen
      command_topic: "homeassistant/lock/door/command"
      payload_press: "1"
      device_class: update
    - name: Schloss Haustür Neustart Esp32 Bridge
      command_topic: "homeassistant/lock/door/command"
      payload_press: "7"
      device_class: restart
    - name: Schloss Haustür Zustand wechseln
      command_topic: "homeassistant/lock/door/command"
      payload_press: "5"
      icon: mdi:toggle-switch
    - name: Schloss Haustür öffnen
      command_topic: "homeassistant/lock/door/command"
      payload_press: "4"
      icon: mdi:door-open
  sensor:
    - name: Aktivität RAW Schloss Haustür
      state_topic: "homeassistant/lock/door/task"
      icon: mdi:home-lightning-bolt-outline
    - name: Signalstärke Schloss Haustür
      state_topic: "homeassistant/lock/door/rssi"
      device_class: signal_strength
      
sensor:
  - platform: template
    sensors:
      zustand_schloss_haustur:
        friendly_name: "Schloss Haustür Zustand"
        value_template: >-
          {% if is_state('sensor.aktivitat_raw_schloss_haustur', 'waiting') %}
            Bereit
          {% elif is_state('sensor.aktivitat_raw_schloss_haustur', 'working') %}
            Kommando ausführen
          {% elif is_state('sensor.aktivitat_raw_schloss_haustur', 'unknown') %}
            Unbekannt
          {% else %}
            {{ states('sensor.aktivitat_raw_schloss_haustur') }}
          {% endif %}
        icon_template: >-
          {% if is_state('ssensor.aktivitat_raw_schloss_haustur', 'waiting') %}
            mdi:sleep
          {% elif is_state('sensor.aktivitat_raw_schloss_haustur', 'working') %}
            mdi:cog
          {% elif is_state('sensor.aktivitat_raw_schloss_haustur', 'unknown') %}
            mdi:help-circle
          {% else %}
            mdi:home
          {% endif %}
